// components/email/email-template.tsx
import * as React from 'react';

interface EmailTemplateProps {
  quote: string;
  subscriptionMessage?: string; // Add an optional message for subscriptions
  unsubscribeUrl?: string; 
}

export const EmailTemplate: React.FC<Readonly<EmailTemplateProps>> = ({
  quote,
  subscriptionMessage,
  unsubscribeUrl,
}) => (
  <div style={{ fontFamily: 'Arial, sans-serif', lineHeight: '1.6', color: '#333' }}>
    <div style={{ maxWidth: '600px', margin: '20px auto', padding: '20px', border: '1px solid #eee', borderRadius: '8px' }}>
      <h1 style={{ fontSize: '24px', color: '#444', marginBottom: '20px', textAlign: 'center' }}>
        Your AI Generated Quote
      </h1>
      <blockquote style={{ fontSize: '18px', margin: '20px 0', padding: '15px 20px', borderLeft: '5px solid #5c67f2', backgroundColor: '#f9f9f9', fontStyle: 'italic' }}>
        &quot;{quote}&quot;
      </blockquote>
      
      {/* **MODIFICATION HERE** */}
      {/* Conditionally render the subscription message if it exists */}
      {subscriptionMessage && (
        <p style={{ fontSize: '16px', textAlign: 'center', color: '#555', marginTop: '20px' }}>
          {subscriptionMessage}
        </p>
      )}

      <div style={{ fontSize: '14px', color: '#777', marginTop: '30px', textAlign: 'center' }}>
        <p>Generated by Your AI Quote App</p>
        {unsubscribeUrl && (
          <p style={{ marginTop: '10px', fontSize: '12px' }}>
            Don&apos;t want to receive these daily? <a href={unsubscribeUrl} style={{ color: '#5c67f2', textDecoration: 'underline' }}>Unsubscribe</a>.
          </p>
        )}
      </div>
    </div>
  </div>
);

export default EmailTemplate;
